[project]
name = "top-agent-comparison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ag2>=0.9.9",
    "crewai>=0.165.1",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.31",
    "pyautogen>=0.10.0",
]
